### ISSUE TITLE
Support multiple deploy targets (i.e., add support for Fennec)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/dynamicua_update_script#2]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1163759 for some background info.

I'll try to cook up a patch that makes this happen tomorrow. And then somebody who is good at shell scripting can find all the bugs :pizza:

**Comment by floatingatoll** [comment]
If it helps, you can focus on patching the script to work _only_ with Fennec, and then I can integrate the patch and the old script so they function correctly together.

**Comment by miketaylr** [comment]
Ah cool. Sounds good @floatingatoll. Thanks!

**Comment by miketaylr** [comment]
FWIW, I think we should wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1164580 to land before proceeding with this (but I'll start working on my patch in a bit). That way we don't have to fork any logic for what gets cleaned up by sed.

**Comment by miketaylr** [comment]
Alright, here's my take on how this would work just for Fennec: 

https://gist.githubusercontent.com/miketaylr/2f513636f89f5e80773c/raw/cd8f3a72e611c8de47df6ea72e8cd471143e47ef/update-fennec.sh

Other than pointing to the right file and using the right GUID, I've tweaked the sed command to also remove `#filter slashslash` and empty lines, in addition to comments.

``` diff
< FILE_URL="https://hg.mozilla.org/mozilla-central/raw-file/tip/b2g/app/ua-update.json.in"
---
> FILE_URL="https://hg.mozilla.org/mozilla-central/raw-file/tip/mobile/android/app/ua-update.json.in"
6,8c6,8
< FILE_LATEST_REVISION=$(curl -s https://hg.mozilla.org/mozilla-central/file/tip/b2g/app/ua-update.json.in | grep -A1 '<td>changeset' | awk -F '[">]' '{print $9}' | awk -F '[</a]' '{print $1}' | grep -v '^$')
< B2G_APP_ID="{3c2e2abc-06d4-11e1-ac3b-374f68613e61}"
< FILENAME=$B2G_APP_ID
---
> FILE_LATEST_REVISION=$(curl -s https://hg.mozilla.org/mozilla-central/file/tip/mobile/android/app/ua-update.json.in | grep -A1 '<td>changeset' | awk -F '[">]' '{print $9}' | awk -F '[</a]' '{print $1}' | grep -v '^$')
> FENNEC_APP_ID="{aa3c5121-dab2-40e2-81ca-7ea25febc110}"
> FILENAME=$FENNEC_APP_ID
31c31
<     curl -s https://hg.mozilla.org/mozilla-central/file/tip/b2g/app/ua-update.json.in | grep -A1 '<td>changeset' | awk -F '[">]' '{print $9}' | awk -F '[</a]' '{print $1}' | grep -v '^$' > $CODE_DIR/$FILE_REVISION_NAME
---
>     curl -s https://hg.mozilla.org/mozilla-central/file/tip/mobile/android/app/ua-update.json.in | grep -A1 '<td>changeset' | awk -F '[">]' '{print $9}' | awk -F '[</a]' '{print $1}' | grep -v '^$' > $CODE_DIR/$FILE_REVISION_NAME
45,46c45,46
< # remove JS comments from file
< sed -i 's/\/\/.*$//g' $VERSION_DIR/$FILENAME
---
> # remove comments, preprocessor directive and empty lines from file
> sed -i '' 's/\/\/.*$//g; s/#filter slashslash//; /^ *$/d' $VERSION_DIR/$FILENAME
```

**Comment by miketaylr** [comment]
> FWIW, I think we should wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1164580 to land

Actually, we probably don't need to wait on 1164580 (but we can). The only thing that really does, for the purposes of this script, is add `#filter slashslash` to ua-update.json.in. sed isn't going to care if it's there or not.

**Comment by miketaylr** [comment]
OK. 1164580 has been r+'d and checkin-needed is set. So it's probably safe to proceed @floatingatoll. :+1:

**Comment by miketaylr** [comment]
And now it's landed on master.

**Comment by floatingatoll** [comment]
Pull #3 is tracking my work on this, and is ready for review and (my) testing. Most of the commits are cleanup, with the final few being the actual changes to sed processing and to add the new fennec endpoint.

**Comment by floatingatoll** [comment]
Update script deployed and generating files as expected.
